--// insert into referances 4 timezone
-- Migration SQL that makes the change goes here.
INSERT INTO referances VALUES (601,'TimeZone','Etc/GMT+12','(GMT-12:00)International Date Line West','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (602,'TimeZone','Etc/GMT+12','(GMT-12:00)国际日期变更线以西','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (603,'TimeZone','Pacific/Apia','(GMT-11:00)Midway Island, Samoa','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (604,'TimeZone','Pacific/Apia','(GMT-11:00)中途岛，萨摩亚','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (605,'TimeZone','Pacific/Honolulu','(GMT-10:00)Hawaii','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (606,'TimeZone','Pacific/Honolulu','(GMT-10:00)夏威夷','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (607,'TimeZone','America/Anchorage','(GMT-09:00)Alaska','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (608,'TimeZone','America/Anchorage','(GMT-09:00)阿拉斯加州','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (609,'TimeZone','America/Los_Angeles','(GMT-08:00)Pacific Time (US & Canada); Tijuana','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (610,'TimeZone','America/Los_Angeles','(GMT-08:00)太平洋时间（美国和加拿大）;蒂华纳','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (611,'TimeZone','America/Phoenix','(GMT-07:00)Arizona','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (612,'TimeZone','America/Phoenix','(GMT-07:00)亚利桑那','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (613,'TimeZone','America/Denver','(GMT-07:00)Mountain Time (US & Canada)','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (614,'TimeZone','America/Denver','(GMT-07:00)山地时间（美国和加拿大）','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (615,'TimeZone','America/Chihuahua','(GMT-07:00)Chihuahua, La Paz, Mazatlan','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (616,'TimeZone','America/Chihuahua','(GMT-07:00)奇瓦瓦，拉巴斯，马萨特兰','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (617,'TimeZone','America/Managua','(GMT-06:00)Central America','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (618,'TimeZone','America/Managua','(GMT-06:00)中美洲','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (619,'TimeZone','America/Regina','(GMT-06:00)Saskatchewan','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (620,'TimeZone','America/Regina','(GMT-06:00)萨斯喀彻温省','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (621,'TimeZone','America/Mexico_City','(GMT-06:00)Guadalajara, Mexico City, Monterrey','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (622,'TimeZone','America/Mexico_City','(GMT-06:00)瓜达拉哈拉，墨西哥城，蒙特雷','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (623,'TimeZone','America/Chicago','(GMT-06:00)Central Time (US & Canada)','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (624,'TimeZone','America/Chicago','(GMT-06:00)中部时间（美国和加拿大）','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (625,'TimeZone','America/Indianapolis','(GMT-05:00)Indiana (East)','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (626,'TimeZone','America/Indianapolis','(GMT-05:00)印地安那（东）','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (627,'TimeZone','America/Bogota','(GMT-05:00)Bogota, Lima, Quito','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (628,'TimeZone','America/Bogota','(GMT-05:00)波哥大，利马，基多','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (629,'TimeZone','America/New_York','(GMT-05:00)Eastern Time (US & Canada)','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (630,'TimeZone','America/New_York','(GMT-05:00)东部时间（美国和加拿大）','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (631,'TimeZone','America/Caracas','(GMT-04:00)Caracas, La Paz','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (632,'TimeZone','America/Caracas','(GMT-04:00)加拉加斯，拉巴斯','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (633,'TimeZone','America/Santiago','(GMT-04:00)Santiago','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (634,'TimeZone','America/Santiago','(GMT-04:00)圣地亚哥','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (635,'TimeZone','America/Halifax','(GMT-04:00)Atlantic Time (Canada)','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (636,'TimeZone','America/Halifax','(GMT-04:00)大西洋时间（加拿大）','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (637,'TimeZone','America/St_Johns','(GMT-03:30)Newfoundland','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (638,'TimeZone','America/St_Johns','(GMT-03:30)纽芬兰','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (639,'TimeZone','America/Buenos_Aires','(GMT-03:00)Buenos Aires, Georgetown','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (640,'TimeZone','America/Buenos_Aires','(GMT-03:00)布宜诺斯艾利斯，乔治敦','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (641,'TimeZone','America/Godthab','(GMT-03:00)Greenland','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (642,'TimeZone','America/Godthab','(GMT-03:00)格陵兰','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (643,'TimeZone','America/Sao_Paulo','(GMT-03:00)Brasilia','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (644,'TimeZone','America/Sao_Paulo','(GMT-03:00)巴西利亚','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (645,'TimeZone','America/Noronha','(GMT-02:00)Mid-Atlantic','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (646,'TimeZone','America/Noronha','(GMT-02:00)中大西洋','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (647,'TimeZone','Atlantic/Cape_Verde','(GMT-01:00)Cape Verde Is.','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (648,'TimeZone','Atlantic/Cape_Verde','(GMT-01:00)佛得角是。','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (649,'TimeZone','Atlantic/Azores','(GMT-01:00)Azores','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (650,'TimeZone','Atlantic/Azores','(GMT-01:00)亚速尔群岛','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (651,'TimeZone','Africa/Casablanca','(GMT-00:00)Casablanca, Monrovia','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (652,'TimeZone','Africa/Casablanca','(GMT-00:00)卡萨布兰卡，蒙罗维亚','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (653,'TimeZone','Europe/London','(GMT-00:00)Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (654,'TimeZone','Europe/London','(GMT-00:00)格林威治标准时间：都柏林，爱丁堡，里斯本，伦敦','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (655,'TimeZone','Africa/Lagos','(GMT+01:00)West Central Africa','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (656,'TimeZone','Africa/Lagos','(GMT+01:00)西中非','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (657,'TimeZone','Europe/Berlin','(GMT+01:00)Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (658,'TimeZone','Europe/Berlin','(GMT+01:00)阿姆斯特丹，柏林，伯恩，罗马，斯德哥尔摩，维也纳','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (659,'TimeZone','Europe/Paris','(GMT+01:00)Brussels, Copenhagen, Madrid, Paris','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (660,'TimeZone','Europe/Paris','(GMT+01:00)布鲁塞尔，哥本哈根，马德里，巴黎','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (661,'TimeZone','Europe/Sarajevo','(GMT+01:00)Sarajevo, Skopje, Warsaw, Zagreb','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (662,'TimeZone','Europe/Sarajevo','(GMT+01:00)萨拉热窝，斯科普里，华沙，萨格勒布','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (663,'TimeZone','Europe/Belgrade','(GMT+01:00)Belgrade, Bratislava, Budapest, Ljubljana, Prague','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (664,'TimeZone','Europe/Belgrade','(GMT+01:00)贝尔格莱德，布拉迪斯拉发，布达佩斯，卢布尔雅那，布拉格','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (665,'TimeZone','Africa/Johannesburg','(GMT+02:00)Harare, Pretoria','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (666,'TimeZone','Africa/Johannesburg','(GMT+02:00)哈拉雷，比勒陀利亚','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (667,'TimeZone','Asia/Jerusalem','(GMT+02:00)Jerusalem','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (668,'TimeZone','Asia/Jerusalem','(GMT+02:00)耶路撒冷','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (669,'TimeZone','Europe/Istanbul','(GMT+02:00)Athens, Istanbul, Minsk','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (670,'TimeZone','Europe/Istanbul','(GMT+02:00)雅典，伊斯坦布尔，明斯克','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (671,'TimeZone','Europe/Helsinki','(GMT+02:00)Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (672,'TimeZone','Europe/Helsinki','(GMT+02:00)赫尔辛基，基辅，里加，索非亚，塔林，维尔纽斯','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (673,'TimeZone','Africa/Cairo','(GMT+02:00)Cairo','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (674,'TimeZone','Africa/Cairo','(GMT+02:00)开罗','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (675,'TimeZone','Europe/Bucharest','(GMT+02:00)Bucharest','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (676,'TimeZone','Europe/Bucharest','(GMT+02:00)布加勒斯特','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (677,'TimeZone','Africa/Nairobi','(GMT+03:00)Nairobi','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (678,'TimeZone','Africa/Nairobi','(GMT+03:00)内罗毕','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (679,'TimeZone','Asia/Riyadh','(GMT+03:00)Kuwait, Riyadh','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (680,'TimeZone','Asia/Riyadh','(GMT+03:00)科威特，利雅得','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (681,'TimeZone','Europe/Moscow','(GMT+03:00)Moscow, St. Petersburg, Volgograd','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (682,'TimeZone','Europe/Moscow','(GMT+03:00)莫斯科，圣彼得堡，伏尔加格勒','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (683,'TimeZone','Asia/Baghdad','(GMT+03:00)Baghdad','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (684,'TimeZone','Asia/Baghdad','(GMT+03:00)巴格达','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (685,'TimeZone','Asia/Tehran','(GMT+03:30)Tehran','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (686,'TimeZone','Asia/Tehran','(GMT+03:30)德黑兰','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (687,'TimeZone','Asia/Muscat','(GMT+04:00)Abu Dhabi, Muscat','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (688,'TimeZone','Asia/Muscat','(GMT+04:00)阿布扎比，马斯喀特','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (689,'TimeZone','Asia/Tbilisi','(GMT+04:00)Baku, Tbilisi, Yerevan','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (690,'TimeZone','Asia/Tbilisi','(GMT+04:00)巴库，第比利斯，埃里温','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (691,'TimeZone','Asia/Kabul','(GMT+04:30)Kabul','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (692,'TimeZone','Asia/Kabul','(GMT+04:30)喀布尔','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (693,'TimeZone','Asia/Karachi','(GMT+05:00)Islamabad, Karachi, Tashkent','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (694,'TimeZone','Asia/Karachi','(GMT+05:00)伊斯兰堡，卡拉奇，塔什干','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (695,'TimeZone','Asia/Yekaterinburg','(GMT+05:00)Ekaterinburg','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (696,'TimeZone','Asia/Yekaterinburg','(GMT+05:00)叶卡捷琳堡','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (697,'TimeZone','Asia/Calcutta','(GMT+05:30)Chennai, Kolkata, Mumbai, New Delhi','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (698,'TimeZone','Asia/Calcutta','(GMT+05:30)金奈，加尔各答，孟买，新德里','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (699,'TimeZone','Asia/Katmandu','(GMT+05:45)Kathmandu','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (700,'TimeZone','Asia/Katmandu','(GMT+05:45)加德满都','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (701,'TimeZone','Asia/Colombo','(GMT+06:00)Sri Jayawardenepura','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (702,'TimeZone','Asia/Colombo','(GMT+06:00)斯里兰卡登普拉','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (703,'TimeZone','Asia/Dhaka','(GMT+06:00)Astana, Dhaka','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (704,'TimeZone','Asia/Dhaka','(GMT+06:00)阿斯塔纳，达卡','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (705,'TimeZone','Asia/Novosibirsk','(GMT+06:00)Almaty, Novosibirsk','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (706,'TimeZone','Asia/Novosibirsk','(GMT+06:00)阿拉木图，新西伯利亚','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (707,'TimeZone','Asia/Rangoon','(GMT+06:30)Rangoon','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (708,'TimeZone','Asia/Rangoon','(GMT+06:30)仰光','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (709,'TimeZone','Asia/Bangkok','(GMT+07:00)Bangkok, Hanoi, Jakarta','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (710,'TimeZone','Asia/Bangkok','(GMT+07:00)曼谷，河内，雅加达','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (711,'TimeZone','Asia/Krasnoyarsk','(GMT+07:00)Krasnoyarsk','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (712,'TimeZone','Asia/Krasnoyarsk','(GMT+07:00)克拉斯诺亚尔斯克','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (713,'TimeZone','Australia/Perth','(GMT+08:00)Perth','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (714,'TimeZone','Australia/Perth','(GMT+08:00)珀斯','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (715,'TimeZone','Asia/Taipei','(GMT+08:00)Taipei','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (716,'TimeZone','Asia/Taipei','(GMT+08:00)台北','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (717,'TimeZone','Asia/Singapore','(GMT+08:00)Kuala Lumpur, Singapore','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (718,'TimeZone','Asia/Singapore','(GMT+08:00)吉隆坡，新加坡','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (719,'TimeZone','Asia/Hong_Kong','(GMT+08:00)Beijing, Chongqing, Hong Kong, Urumqi','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (720,'TimeZone','Asia/Hong_Kong','(GMT+08:00)北京，重庆，香港，乌鲁木齐','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (721,'TimeZone','Asia/Irkutsk','(GMT+08:00)Irkutsk, Ulaan Bataar','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (722,'TimeZone','Asia/Irkutsk','(GMT+08:00)伊尔库次克，乌兰巴托','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (723,'TimeZone','Asia/Tokyo','(GMT+09:00)Osaka, Sapporo, Tokyo','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (724,'TimeZone','Asia/Tokyo','(GMT+09:00)大阪，札幌，东京','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (725,'TimeZone','Asia/Seoul','(GMT+09:00)Seoul','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (726,'TimeZone','Asia/Seoul','(GMT+09:00)汉城','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (727,'TimeZone','Asia/Yakutsk','(GMT+09:00)Yakutsk','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (728,'TimeZone','Asia/Yakutsk','(GMT+09:00)雅库茨克','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (729,'TimeZone','Australia/Darwin','(GMT+09:30)Darwin','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (730,'TimeZone','Australia/Darwin','(GMT+09:30)达尔文','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (731,'TimeZone','Australia/Adelaide','(GMT+09:30)Adelaide','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (732,'TimeZone','Australia/Adelaide','(GMT+09:30)阿德莱德','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (733,'TimeZone','Pacific/Guam','(GMT+10:00)Guam, Port Moresby','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (734,'TimeZone','Pacific/Guam','(GMT+10:00)关岛，莫尔兹比港','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (735,'TimeZone','Australia/Brisbane','(GMT+10:00)Brisbane','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (736,'TimeZone','Australia/Brisbane','(GMT+10:00)布里斯班','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (737,'TimeZone','Asia/Vladivostok','(GMT+10:00)Vladivostok','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (738,'TimeZone','Asia/Vladivostok','(GMT+10:00)海参崴','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (739,'TimeZone','Australia/Hobart','(GMT+10:00)Hobart','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (740,'TimeZone','Australia/Hobart','(GMT+10:00)霍巴特','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (741,'TimeZone','Australia/Sydney','(GMT+10:00)Canberra, Melbourne, Sydney','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (742,'TimeZone','Australia/Sydney','(GMT+10:00)堪培拉，墨尔本，悉尼','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (743,'TimeZone','Asia/Magadan','(GMT+11:00)Magadan, Solomon Is., New Caledonia','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (744,'TimeZone','Asia/Magadan','(GMT+11:00)马加丹，所罗门群岛。，新喀里多尼亚','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (745,'TimeZone','Pacific/Fiji','(GMT+12:00)Fiji, Kamchatka, Marshall Is.','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (746,'TimeZone','Pacific/Fiji','(GMT+12:00)斐济，堪察加半岛，马绍尔群岛。','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (747,'TimeZone','Pacific/Auckland','(GMT+12:00)Auckland, Wellington','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (748,'TimeZone','Pacific/Auckland','(GMT+12:00)奥克兰，惠灵顿','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (749,'TimeZone','Pacific/Tongatapu','(GMT+13:00)Nukualofa','en','','createdBy',SYSDATE(),'createdBy',SYSDATE());
INSERT INTO referances VALUES (750,'TimeZone','Pacific/Tongatapu','(GMT+13:00)努库阿洛法','zh','','createdBy',SYSDATE(),'createdBy',SYSDATE());



--//@UNDO
-- SQL to undo the change goes here.
delete from referances where id >=601 and id <=750;

